services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - /srv/ingress:/etc/nginx/conf.d/
      - /root/.acme.sh/*.zxyxyhome.duckdns.org_ecc/:/etc/ssl/certs/nginx/
      - /srv/proxysetting:/srv/proxysetting
    ports:
      - 80:80
      - 443:443

  duckdns:
    image: linuxserver/duckdns:version-b9e2cafd
    container_name: duckdns
    network_mode: host
    environment:
      - SUBDOMAINS=zxyxy
      - TOKEN=bd57877e-769e-44f7-ac6e-8b21916d9308
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:1.41.2
    container_name: plex
    environment:
      - PUID=10000
      - PGID=100
      - TZ=Etc/UTC
      - VERSION=docker
    volumes:
      - /storage01/flexconfig:/config
      - /storage01/share/Video/:/Video
      - /storage01/share/Audio/:/Audio
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"

#  freeipa:
#    image: freeipa/freeipa-server:fedora-41-4.12.2
#    container_name: freeipa-server
#    privileged: true
#    hostname: freya.int.zxyxy.net  # Adjust hostname to reflect subdomain
#    environment:
#      - IPA_SERVER_IP=172.21.0.2    # Your server’s IP within your local network
#      - IPA_REALM=INT.ZXYXY.NET     # Set the realm to your subdomain in uppercase
#      - IPA_DOMAIN=int.zxyxy.net    # Your subdomain
#      - IPA_HOSTNAME=freya.int.zxyxy.net
#      - DM_PASSWORD=dmpassword4136  # Set a strong password
#      - ADMIN_PASSWORD=Nemmas4136
#    volumes:
#      - /srv/ipa/data:/data:Z
#      - /srv/ipa/config:/config:Z
#    ports:
#      - "12080:80"
#      - "12443:443"
#      - "389:389"
#      - "636:636"
#      - "88:88"    # Kerberos
#      - "464:464"  # Kerberos
#      - "12053:53/udp"  # DNS (for internal domain resolution)
#    restart: unless-stopped
