services:
#  ingress:
#    image: nginx
#    restart: always
#    volumes:
#      - ./config/:/etc/nginx/conf.d/
#      - /root/.acme.sh/*.zxyxyhome.duckdns.org_ecc/:/etc/ssl/certs/nginx/
#    ports:
#      - 80:80
#      - 443:443

  mariadb:
    image: mariadb:11.0.1-rc-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: fire11password
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - /srv/mariadb:/var/lib/mysql

  adminer:
    depends_on:
      - mariadb
    image: adminer
    restart: always
    ports:
      - 8081:8080

  php:
    image: php:fpm
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/www/html:/var/www/html
  #    - /srv/php/www.conf:/usr/local/etc/php-fpm.d/www.conf

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - /var/www/html:/var/www/html
      - /srv/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
    ports:
      - 80:80
    links:
      - php
