---
- name: manage packages
  hosts: localhost
  vars:
    docker_distribution: archlinux
    docker_ansible_requirements: true
  pre_tasks:
    - name: Upgrade system
      become: true
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: Remove packages
      become: true
      pacman:
        name:
          - cabal-fmt
          - cabal-install
          - ghc
          - ghc-static
          - ghc-libs
          - protobuf
          - virtualbox-host-modules-arch
        state: absent
        force: yes

    - name: Install packages
      become: true
      pacman:
        name:
          - ansible
          - ant
          - base-devel
          - boost
          - boost-libs
          - blueman
          - ca-certificates
          - ca-certificates-mozilla
          - clang
          - docker
          - gtk2
          - gperf
          - junit
          - jq
          - keepass
          - kubectx
          - kubens
          - kubectl
          - linux-lts-headers
          - mc
          - mosquitto
          - npm
          - ncurses
          - ntp
          - openssh
          - python-protobuf
          - python-grpcio-tools
          - python-pylint
          - python-setuptools
          - python-virtualenv
          - protobuf
          - samba
          - scons
          - sudo
          - sshfs
          - terraform
          - traceroute
          - jdk11-openjdk
          - tmux
          - screen
          - vim
          - vlc
          - zsh
          - zip
          - wget
        state: present

    - name: Install X packages
      become: true
      pacman:
        name:
          - arandr
          - caja
          - chromium
          - xf86-video-intel
          - dmenu
          - xterm
          - lightdm
          - i3-wm
          - lightdm-gtk-greeter
          - libmtp
          - mate-terminal
          - i3status
          - pavucontrol
          - network-manager-applet
          - mplayer
          - pasystray
          - okular
          - gtk2
          - xdotool
        state: present

  collections:
    - kewlfft.aur
  roles:
  - { role: andrewrothstein.go, become: yes }
  - { role: andrewrothstein.k9s, become: yes }
  - { role: andrewrothstein.kubernetes-helm, become: yes }
  - { role: andrewrothstein.kubelogin, become: yes }
  - { role: andrewrothstein.istio, become: yes }
#  - { role: buluma.azure_cli, become: yes }

  tasks:
    - name: Enable services
      become: yes
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - docker
        - sshd

# create aur_builder to install aur packages
    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install aur packages
      aur:
        name: "{{ item }}"
        use: makepkg
        state: present
        ignore_arch: yes
      loop:
        - azure-cli
        - avro-c
        - brave-bin
        - dbeaver-git
        - google-chrome
        - kcat-cli
        - microsoft-edge-stable-bin
        - themix-gui-git
        - themix-plugin-base16-git
        - themix-icons-numix-git
        - themix-theme-oomox-git
        - themix-export-spotify-git
        - themix-icons-archdroid-git
        - themix-icons-gnome-colors-git
        - themix-icons-papirus-git
        - themix-icons-suru-plus-git
        - themix-icons-suru-plus-aspromauros-git
        - themix-import-images-git
        - themix-full-git
        - virtualbox-guest-iso-dev
        - visual-studio-code-bin
        - c-client
        - php82
        - php82-cli
        - php82-curl
        - php82-phar
        - php82-pear
        - php82-mysql
        - php82-dba
        - php82-composer
        - 7-zip-full
        - httpfs2-2gbplus
        - httpdirfs
#        - ttf-ms-win10-auto
#        - ttf-ms-win11-auto
#        - ttf-ms-fonts

      become: yes
      become_user: aur_builder

    - name: Create Hack font directory
      become: yes
      ansible.builtin.file:
        path: /usr/share/fonts/Hack
        state: directory
        mode: '0755'

    - name: Install hack font
      become: yes
      copy:
        src: files/Hack-Regular.ttf
        dest: /usr/share/fonts/Hack
        force: no
      loop:
        - files/Hack-Regular.ttf
        - files/Hack-Bold.ttf
        - files/Hack-Italic.ttf
        - files/Hack-BoldItalic.ttf

    - name: php symlink
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      become: yes
      loop:
        - { src: "/usr/bin/php82", dest: "/usr/bin/php"}
        - { src: "/usr/bin/composer82", dest: "/usr/bin/composer"}
