---
- name: wsl debian setting
  become: yes
  hosts:
    - localhost
  collections:
    - pandemonium1986.k8s_toolbox
    - serdigital64.infrastructure

  tasks:
    - name: Install packages
      become: true
      apt:
        name:
          - vim
          - git
          - mc
          - nodejs
          - openjdk-17-jdk
          - zsh
          - tmux
          - screen
          - python3-venv
          - neovim
        state: present
        update_cache: yes

    - name: install python virtual env
      become: true
      pip:
        name:
          - virtualenv


#
