---
- name: wsl profile setting
  hosts:
    - localhost

  vars:
    user: "{{ ansible_facts.env.USER }}"
    envs: |
      PATH=$PATH:/home/{{ user }}/tools/wq
      alias gitg="git log --all --decorate --oneline --graph"
      alias klogf="kubectl logs -f "
      alias ls='ls --color=auto'
      alias f="kubectl logs -f `kubectl get po --sort-by=.status.startTime | tail -1 | awk '{ print $1 }'`"
      alias h="helm"
      alias k="kubectl"
      alias t="terraform"
      EDITOR=vim

  tasks:
    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: ansible create directory Devel
      file:
        path: "/home/{{ user }}/Devel"
        state: directory

    - name: Clone a github repository
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        clone: yes
        update: yes

    - name: Clone a powerlevel10k repository
      git:
        repo:  https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerline10k"
        clone: yes
        update: yes

    - name: zshrc
      become: yes
      copy:
        src: files/zshrc
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        mode: 0644

    - name: copy ssh
      copy:
        src: /mnt/c/Users/{{ user }}/.ssh
        dest: /home/{{ user }}
        directory_mode: "0700"
        mode: "0600"
      tags:
        - dircontent

    - name: Insert/Update aliases in bashrc
      blockinfile:
        path: /home/{{ user }}/.bashrc
        block: "{{ envs }}"

    - name: Insert/Update aliases in profile
      blockinfile:
        path: /home/{{ user }}/.profile
        block: "{{ envs }}"
        create: "true"
