---
- name: Wsl profile setting
  hosts:
    - localhost

  vars:
    user: "{{ ansible_facts.env.USER }}"
    envs: |
      PATH=$PATH:/home/{{ user }}/tools/wq
      alias gitg="git log --all --decorate --oneline --graph"
      alias klogf="kubectl logs -f "
      alias ls='ls --color=auto'
      alias f="kubectl logs -f `kubectl get po --sort-by=.status.startTime | tail -1 | awk '{ print $1 }'`"
      alias h="helm"
      alias k="kubectl"
      alias t="terraform"
      alias php='docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.2-cli php'
      alias composer='docker run --rm --interactive --tty --volume $PWD:/app composer'
      EDITOR=vim

  tasks:
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: Ansible create directory Devel
      ansible.builtin.file:
        path: "/home/{{ user }}/Devel"
        state: directory
        mode: "0755"

    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        clone: true
        update: true

    - name: Clone a powerlevel10k repository
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerline10k"
        clone: true
        update: true

    - name: Zshrc
      ansible.builtin.copy:
        src: files/zshrc
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        mode: "0644"

    - name: Gitconfig
      ansible.builtin.copy:
        src: files/zxyxy/gitconfig
        dest: "/home/{{ user }}/.gitconfig"
        owner: "{{ user }}"
        mode: "0600"

    - name: Ansible create transmission directory
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /storage02/kube/torrent-a/toDownload

    - name: Copying config files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        mode: "0655"
      loop:
        - { src: "files/{{ user }}/settings.ini", dest: "/home/{{ user }}/.config/gtk-3.0/settings.ini" }
