---
- name: wsl debian setting
  become: yes
  hosts:
    - localhost
  collections:
    - pandemonium1986.k8s_toolbox
    - serdigital64.infrastructure
    - ivansible.devel
  roles:
    - mrlesmithjr.nodejs

  tasks:
    - name: Install packages
      become: true
      apt:
        name:
          - vim
          - git
          - mc
          - openjdk-17-jdk
          - zsh
          - tmux
          - screen
          - python3-venv
        state: present
        update_cache: yes

    - name: remove packages
      become: true
      apt:
        name:
          - nodejs
        state: absent

    - name: install python virtual env
      become: true
      pip:
        name:
          - virtualenv

#    - name: Install cdk8s-cli node.js package globally.
#      community.general.npm:
#        name: cdk8s-cli
#        global: true
#
