---
- name: wsl profile setting
  hosts:
    - localhost

  vars:
    user: ameszely
    envs: |
      PATH=$PATH:/home/{{ user }}/bin
      alias gitg="git log --all --decorate --oneline --graph"
      alias klogf="kubectl logs -f "
      alias egrep='egrep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias grep='grep --color=auto'
      alias helga='helm list | grep '
      alias hgv='helm get values '
      alias kdcat='kubectl describe deploy'
      alias kddcat='kubectl get -o yaml deploy'
      alias kddown='kubectl scale deploy  --replicas=0'
      alias kdrm='kubectl delete deploy'
      alias kdup='kubectl scale deploy  --replicas=1'
      alias kdvi='kubectl edit deploy'
      alias kex='kubectl exec -it'
      alias kicat='kubectl describe ingress'
      alias kimi='python3 /oper/imagetags.py'
      alias kirm='kubectl delete ingress'
      alias kivi='kubectl edit ingress'
      alias klogs='kubectl logs'
      alias kpcat='kubectl describe po'
      alias kpdcat='kubectl get -o yaml po'
      alias kprm='kubectl delete po'
      alias kpvi='kubectl edit po'
      alias kscat='kubectl describe service'
      alias ksrm='kubectl delete service'
      alias ksvi='kubectl edit service'
      alias l='ls -CF'
      alias la='ls -A'
      alias ll='ls -lah'
      alias llh='helm list'
      alias llkc='kubectl get configmap'
      alias llkd='kubectl get deploy'
      alias llki='kubectl get ingress'
      alias llkp='kubectl get po'
      alias llks='kubectl get services'
      alias ls='ls --color=auto'
      alias plog='bash ~/.pod-logger.sh'
      alias plogp='bash ~/.pod-logger-prev.sh'
      alias xo='/oper/xo'
      alias f="kubectl logs -f `kubectl get po --sort-by=.status.startTime | tail -1 | awk '{ print $1 }'`"
      alias h="helm"
      alias k="kubectl"
      alias t="terraform"
      alias nodes="kubectl get nodes -o json | jq \".items[]|{name:.metadata.name, version:.status.nodeInfo.kubeletVersion, taints:.spec.taints}\""
      EDITOR=vim
      export TF_VAR_tags='{"DMGMoriScope"   = "DIGITAL-Services", "DMGMoriService" = "WERKBLiQ"}'

  tasks:
    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: ansible create directory Devel
      file:
        path: "/home/{{ user }}/Devel"
        state: directory

    - name: Clone a github repository
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        clone: yes
        update: yes

    - name: Clone a powerlevel10k repository
      git:
        repo:  https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerline10k"
        clone: yes
        update: yes

    - name: zshrc
      become: yes
      copy:
        src: files/zshrc
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        mode: 0644

    - name: copy ssh
      copy:
        src: /mnt/c/Users/{{ user }}/.ssh
        dest: /home/{{ user }}
        directory_mode: "0700"
        mode: "0600"
      tags:
        - dircontent

    - name: Insert/Update aliases in bashrc
      blockinfile:
        path: /home/{{ user }}/.bashrc
        block: "{{ envs }}"
        create: true

    - name: Insert/Update aliases in bashrc
      blockinfile:
        path: /home/{{ user }}/.zshrc
        block: "{{ envs }}"
        create: true

    - name: Insert/Update aliases in profile
      blockinfile:
        path: /home/{{ user }}/.profile
        block: "{{ envs }}"
        create: true

    - name: whitetulip bin
      become:
      file:
        path: ~/bin
        state: directory
        mode: 0770
