---
- name: manage packages
  become: yes
  hosts:
    - localhost
  roles:
    - { role: andrewrothstein.go, become: yes }
  pre_tasks:
    - name: Upgrade system
      become: true
      community.general.pacman:
        update_cache: yes
        upgrade: yes

  tasks:
    - name: Install packages
      become: true
      pacman:
        name:
          - git
          - screen
          - sshfs
          - zsh
          - tmux
          - vim
          - ant
          - base-devel
          - boost
          - boost-libs
          - blueman
          - clang
          - gtk2
          - gperf
          - junit
          - kubectx
          - kubens
          - kubectl
          - linux-lts-headers
          - make
          - mc
          - npm
          - ncurses
          - nodejs
          - ntp
          - openssh
          - python
          - python-jedi
          - python-pylint
          - python-pylint-venv
          - python-setuptools
          - python-virtualenv
          - sudo
          - sshfs
          - terraform
          - traceroute
          - jdk11-openjdk
          - tmux
          - screen
          - vim
          - vlc
          - zsh
          - zip
          - wget
        state: present

#    - name: Ensure group "global-users" exists with correct gid
#      ansible.builtin.group:
#        name: global-users
#        state: present
#        gid: 100

    - name: enable wheel group in sudoers
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^%wheel ALL=(ALL:ALL) ALL'
        line: '%wheel ALL=(ALL:ALL) ALL'

    - name: Install npm packages
      become: true
      community.general.npm:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        global: true
      loop:
        - name: "@angular/cli"
          version: 17.0.2
