---
- name: Wsl profile setting
  hosts:
    - localhost

  vars:
    user: ameszely
    envs: |
      PATH=$PATH:/home/{{ user }}/bin
      alias gitg="git log --all --decorate --oneline --graph"
      alias klogf="kubectl logs -f "
      alias egrep='egrep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias grep='grep --color=auto'
      alias helga='helm list | grep '
      alias hgv='helm get values '
      alias kdcat='kubectl describe deploy'
      alias kddcat='kubectl get -o yaml deploy'
      alias kddown='kubectl scale deploy  --replicas=0'
      alias kdrm='kubectl delete deploy'
      alias kdup='kubectl scale deploy  --replicas=1'
      alias kdvi='kubectl edit deploy'
      alias kex='kubectl exec -it'
      alias kicat='kubectl describe ingress'
      alias kimi='python3 /oper/imagetags.py'
      alias kirm='kubectl delete ingress'
      alias kivi='kubectl edit ingress'
      alias klogs='kubectl logs'
      alias kpcat='kubectl describe po'
      alias kpdcat='kubectl get -o yaml po'
      alias kprm='kubectl delete po'
      alias kpvi='kubectl edit po'
      alias kscat='kubectl describe service'
      alias ksrm='kubectl delete service'
      alias ksvi='kubectl edit service'
      alias l='ls -CF'
      alias la='ls -A'
      alias ll='ls -lah'
      alias llh='helm list'
      alias llkc='kubectl get configmap'
      alias llkd='kubectl get deploy'
      alias llki='kubectl get ingress'
      alias llkp='kubectl get po'
      alias llks='kubectl get services'
      alias ls='ls --color=auto'
      alias plog='bash ~/.pod-logger.sh'
      alias plogp='bash ~/.pod-logger-prev.sh'
      alias f="kubectl logs -f `kubectl get po --sort-by=.status.startTime | tail -1 | awk '{ print $1 }'`"
      alias h="helm"
      alias k="kubectl"
      alias t="terraform"
      alias nodes='kubectl get nodes -o json | jq ".items[]|{name:.metadata.name, version:.status.nodeInfo.kubeletVersion, taints:.spec.taints}"'
      alias php='docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:8.2-cli php'
      export TF_VAR_tags='{"DMGMoriScope"   = "DIGITAL-Services", "DMGMoriService" = "WERKBLiQ"}'
      export HELM_EXPERIMENTAL_OCI=1
      export EDITOR=vim
      export CLUSTER_REPO="/home/ameszely/Oper/dev-cluster"
      export OPERATIONS="/home/ameszely/Oper/operations"
      export PATH=$PATH:/home/ameszely/bin:/home/ameszely/.local/bin:/home/ameszely/.cargo/bin
      export ZWIQ_LOG_PATH="/home/ameszely/log/deploy.log"

  tasks:
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: Create directories
      become: true
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        state: directory
      loop:
        - { path: "/home/{{ user }}/Devel", mode: "0755", owner: "{{ user }}"}
        - { path: "/home/{{ user }}/Oper", mode: "0755", owner: "{{ user }}"}
        - { path: "/home/{{ user }}/.ssh", mode: "0700", owner: "{{ user }}"}
        - { path: "/home/{{ user }}/bin", mode: "0700", owner: "{{ user }}"}
        - { path: "/home/{{ user }}/log", mode: "0700", owner: "{{ user }}"}
        - { path: "/home/{{ user }}/mount/freya", mode: "0700", owner: "{{ user }}"}

    - name: Clone a github repository
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "/home/{{ user }}/.oh-my-zsh"
        clone: true
        update: true
        version: master

    - name: Clone a powerlevel10k repository
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user }}/.oh-my-zsh/custom/themes/powerline10k"
        clone: true
        update: true
        version: v1.19.0

    - name: Zshrc
      become: true
      ansible.builtin.copy:
        src: files/zshrc
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        mode: "0644"

#    - name: copy ssh
#      copy:
#        src: /mnt/c/Users/{{ user }}/.ssh
#        dest: /home/{{ user }}
#        directory_mode: "0700"
#        mode: "0600"
#      tags:
#        - dircontent

    - name: Insert/Update aliases in bashrc
      ansible.builtin.blockinfile:
        path: /home/{{ user }}/.bashrc
        block: "{{ envs }}"
        create: true
        mode: "0644"

    - name: Insert/Update aliases in bashrc
      ansible.builtin.blockinfile:
        path: /home/{{ user }}/.zshrc
        block: "{{ envs }}"
        create: true
        mode: "0644"

    - name: Insert/Update aliases in profile
      ansible.builtin.blockinfile:
        path: /home/{{ user }}/.profile
        block: "{{ envs }}"
        create: true
        mode: "0644"

    - name: Fix zsh conf ending
      ansible.builtin.replace:
        path: /home/{{ user }}/.zshrc
        regexp: "\r"
        replace: ""

#      local_action: replace dest=/home/{{ user }}/.zshrc regexp="\r"

    - name: Copying config files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ user }}"
        mode: "0700"
      loop:
        - { src: "files/dmg/gitconfig", dest: "/home/{{ user }}/.gitconfig" }
        - { src: "files/dmg/xo", dest: "/home/{{ user }}/bin/xo" }
        - { src: "files/dmg/vimrc", dest: "/home/{{ user }}/.vimrc" }
        - { src: "files/dmg/zwiq", dest: "/home/{{ user }}/bin/zwiq" }
        - { src: "files/dmg/ssh/config", dest: "/home/{{ user }}/.ssh/config" }
        - { src: "files/ameszely/homebackup.sh", dest: "/home/{{ user }}/bin/homebackup.sh" }

    - name: Backup of home directory
      ansible.builtin.cron:
        name: "home backup"
        minute: "0"
        hour: "13"
        job: "/home/{{ user }}/bin/homebackup.sh > /dev/null"
