---
collections:
- name: pandemonium1986.k8s_toolbox
- name: kewlfft.aur
# - name: serdigital64.infrastructure
# - name: ivansible.devel

roles:
- role: bertvv.samba
- role: gantsign.kubernetes
- name: geerlingguy.docker
- name: geerlingguy.kubernetes
- name: geerlingguy.helm
- name: apkawa.nfs
- name: mrlesmithjr.nodejs
- name: andrewrothstein.kubectl
- name: andrewrothstein.go
- name: andrewrothstein.unarchivedeps
- name: andrewrothstein.k9s
- name: andrewrothstein.kubernetes-helm
- name: andrewrothstein.kubelogin
- name: buluma.azure_cli
- name: andrewrothstein.k3d
- name: andrewrothstein.istio
- name: andrewrothstein.anaconda
- name: andrewrothstein.conda_env
- name: andrewrothstein.azurecli
