---
collections:
- name: pandemonium1986.k8s_toolbox
# - name: serdigital64.infrastructure
# - name: ivansible.devel

roles:
- role: bertvv.samba
- role: gantsign.kubernetes
# - name: geerlingguy.docker
- name: geerlingguy.kubernetes
- name: geerlingguy.helm
- name: apkawa.nfs
- name: mrlesmithjr.nodejs
