---
collections:
- name: pandemonium1986.k8s_toolbox
- name: serdigital64.infrastructure
- name: ivansible.devel

roles:
# - name: geerlingguy.docker
- name: geerlingguy.kubernetes
- name: geerlingguy.helm
- name: bertvv.samba
- name: apkawa.nfs
- name: mrlesmithjr.nodejs
