version: '3.1'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - /srv/ingress:/etc/nginx/conf.d/
      - /srv/nginx.conf:/etc/nginx/nginx.conf
      - /root/.acme.sh/*.zxyxyhome.duckdns.org_ecc/:/etc/ssl/certs/nginx/
      - /srv/proxysetting:/srv/proxysetting
    ports:
      - 80:80
      - 443:443

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /srv/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /srv/mosquitto/passwd.conf:/mosquitto/config/passwd.conf

  plex:
    image: lscr.io/linuxserver/plex:1.40.0
    platform: linux/arm64
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /storage02/flexconfig:/config
      - /storage02/share/Video/:/Video
      - /storage02/share/Audio/:/Audio
    restart: unless-stopped
