version: '3.1'


services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /srv/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /srv/mosquitto/passwd.conf:/mosquitto/config/passwd.conf
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /srv//homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
