hostname: Freya
ansible_host: zxyxyhome.duckdns.org
ansible_user: ansible
ansible_ssh_private_key_file: ansible.key
ansible_become_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65656463306538363037333664656331303933386539343639306334623133383133626537303661
        3962323335386666353563376339323631633430633364650a396531636635633137336237323234
        30663237326266323063303538646662623465616661373464373530646363666565373865616638
        6537663837613664640a373262643830383730373965363636346466366537666361646236613535
        3666

nfs_client: no
nfs_server: yes

nfs_server_shares:
  - path: /storage01
    allow:
      - 127.0.0.1/8
      - 172.0.0.0/8
      - 192.168.10.0/24
    options: (rw,sync,no_subtree_check,no_root_squash)
  - path: /storage02
    allow:
      - 127.0.0.1/8
      - 172.0.0.0/8
      - 192.168.10.0/24
    options: (rw,sync,no_subtree_check,no_root_squash)
#  - path: /storage03
#    allow:
#      - 172.20.0.0/16
#      - 172.21.0.0/16
#      - 192.168.10.0/24

samba_netbios_name: FREYA
samba_server_string: 'Welcome to the Freya file server'
samba_workgroup: znet
samba_realm: int.zxyxy.net
samba_load_homes: true
samba_load_printers: false
samba_create_varwww_symlinks: true
samba_wins_support: false
samba_domain_master: false
samba_preferred_master: true
samba_mitigate_cve_2017_7494: false
#samba_global_include: global-include.conf


samba_shares:
  - name: share
    comment: 'Share'
    path: /storage01/share
    create_mode: 660
    force_create_mode: 660
    directory_mode: 770
    force_directory_mode: 770
    group: users
    writeable: yes
    browseable: yes
#    include_file: share-include.conf

#  - name: vault
#    comment: 'Vault for sensitive files'
#    path: /storage02/vault
#    write_list: zxyxy, lilla
#    read_list: zxyxy, lilla
#    create_mode: 660
#    force_create_mode: 660
#    directory_mode: 770
#    force_directory_mode: 770
#    group: vault
#    browseable: yes
#
#  - name: torrent
#    comment: 'shares for torrent downloadings'
#    path: /storage03/torrent
#    create_mode: 666
#    force_create_mode: 666
#    directory_mode: 777
#    force_directory_mode: 777
#    group: users
#    browseable: yes
#
#  - name: z
#    comment: 'z shares'
#    path: /storage01/z
#    create_mode: 600
#    force_create_mode: 600
#    directory_mode: 700
#    force_directory_mode: 700
#    browseable: yes
#    write_list: zxyxy
#    read_list: zxyxy
#
